Add travis

diff --git a/Task_4/Makefile b/Task_4/Makefile
--- a/Task_4/Makefile
+++ b/Task_4/Makefile
@@ -1,8 +1,10 @@
 SHELL := /bin/bash
 #MAKEFLAGS += --silent
+I := 01 02 04 08
+J := 01 02 04
 
 all: main generate print equals
-.cpp:
+.cpp: quantum.h
 	mpicxx -std=c++11 -Wall -Werror -fopenmp $^ -o $@
 .PHONY: lint
 lint:
@@ -11,16 +13,21 @@ lint:
 test: main equals
 	for way in ./tests/*; do \
 		echo -n -e "$$way \t" ; \
-		./main $$way/A.dat $$way/C.dat < $$way/in.txt > /dev/null; \
-		x=`./equals $$way/B.dat $$way/C.dat` ; \
+		for i in $(I); do \
+			for j in $(J); do \
+				OMP_NUM_THREADS=$$j mpirun -n $$i ./main \
+					$$way/A.dat $$way/C.dat < $$way/in.txt > /dev/null ; \
+				x=`./equals $$way/B.dat $$way/C.dat` ; \
+				if [[ $$x != 1 ]]; then \
+					rm $$way/C.dat ; \
+					echo "FAIL" ; \
+					exit 1 ; \
+				fi \
+			done \
+		done ; \
 		rm $$way/C.dat ; \
-		if [[ $$x != 1 ]]; then \
-			echo "FAIL" ; \
-			exit 1 ; \
-		else \
-			echo "OK" ; \
-		fi \
-	done ;
+		echo "OK" ; \
+	done
 .PHONY: clean
 clean:
 	rm main generate print equals
